services:
  postgres:
    image: postgres:16

    container_name: ai-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_interview

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma

    container_name: ai-chromadb

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - chroma-data:/chroma/chroma

volumes:
  postgres-data:
  chroma-data: